# Generated by Django 4.1.6 on 2023-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeeCalcVals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_value_min", models.IntegerField()),
                ("cart_value_max", models.IntegerField()),
                ("distance_basic_fee", models.IntegerField()),
                ("base_distance", models.IntegerField()),
                ("distance_interval", models.IntegerField()),
                ("distance_interval_fee", models.IntegerField()),
                ("item_amount_start", models.IntegerField()),
                ("item_amount_fee", models.IntegerField()),
                ("bulk_number", models.IntegerField()),
                ("bulk_fee", models.IntegerField()),
                ("delivery_fee_max", models.IntegerField()),
            ],
        ),
    ]
